imports:
    - { resource: services_alias.yml }

services:
    _defaults:
        public: true

    CoreShop\Component\Locale\Context\LocaleContextInterface: '@CoreShop\Component\Locale\Context\CompositeLocaleContext'
    CoreShop\Component\Locale\Context\CompositeLocaleContext:
        public: false

    CoreShop\Component\Locale\Context\PimcoreLocaleContext:
        arguments:
            - '@Pimcore\Localization\LocaleServiceInterface'
        tags:
            - { name: coreshop.context.locale, priority: 100 }

    CoreShop\Component\Locale\Context\FixedLocaleContext:
        tags:
            - { name: coreshop.context.locale, priority: 200 }
